kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     #soft limit
     requests:
      cpu: "512Mi"
      memory: "250m"
      #limits should be atleast or more than requests i.e hard limit.
     limits:
      cpu: "1Gi"
      memory: "500m"

