apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-individual
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef: #refers individual secret values in a file 
          name: secret-doc # This is secrets file name
          key: username  # This is secrets file one key

    - name: password
      valueFrom:
        secretKeyRef:
          name: secret-doc
          key: password
