apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: secret-volume
        mountPath: /usr/share/nginx/html
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
