apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
  - name: nginx
    image: nginx
    - name: username
    env:
    - name: course
      valueFrom:
        secretKeyRef: #refers individual secret values in a file 
           name: pod-secret # This is secrets file name
           key: username  # This is secrets file one key
    - name: password
      valueFrom:
        secretKeyRef:
           name: pod-secret
           key: password
